spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: GSretail0890!@
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
    basedir: .
logging:
  level:
    org:
      springframework:
        security: debug
        boot: debug